### ISSUE TITLE
[Bug] bug title

### ISSUE THREAD

**Issue by zhu-mingye** [streamxhub/streamx#193]
**StreamX Version**:

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system): Centos7

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc. The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.
分支 main
版本 最新

 启动的时候 报错

启动:
[root@master streamx-console-service-1.1.0]# bin/startup.sh
[StreamX] Using APP_BASE:   /usr/local/module/streamx/streamx-console-service-1.1.0
[StreamX] Using APP_HOME:   /usr/local/module/streamx/streamx-console-service-1.1.0
[StreamX] Using JRE_HOME:   /usr/local/module/jdk
[StreamX] Using APP_PID:   /usr/local/module/streamx/streamx-console-service-1.1.0/.pid
[StreamX] Usage: properties file:application.yml
[StreamX] Using HADOOP_HOME:   /usr/local/module/hadoop

报错日志:
Caused by: java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.Log4jLoggerFactory loaded from file:/usr/local/module/streamx/streamx-console-service-1.1.0/lib/slf4j-log4j12-1.7.30.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.impl.Log4jLoggerFactory
        at org.springframework.util.Assert.instanceCheckFailed(Assert.java:702)
        at org.springframework.util.Assert.isInstanceOf(Assert.java:602)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:284)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:104)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:232)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:213)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
        at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:47)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
        at com.streamxhub.streamx.console.StreamXConsole.main(StreamXConsole.java:51)
        ... 5 more

**Stack Trace (if you have one)**:

**Comment by zhu-mingye** [comment]
because the StreamX  branch  choose  main ,  then  building Success but started is error  , after Switching branch 1.0.0 building Success , Launch successfully. Deployment Normal ,
