### ISSUE TITLE
[Bug] flink scala2.12版本提交任务报错

### ISSUE THREAD

**Issue by waywtdcc** [streamxhub/streamx#297]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**:  1.11
* **JVM version** (`java -version`): 1.8
* **OS version** (`uname -a` if on a Unix-like system): linux

### Bug Description
 flink scala2.12版本提交任务报错

### How to Reproduce 
Steps to reproduce the behavior, for example:

Caused by: java.lang.NoClassDefFoundError: scala/Product$class
	at com.streamxhub.streamx.flink.core.SqlError.<init>(SqlCommandParser.scala:377) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$.executeSql(FlinkSqlExecutor.scala:76) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.core.FlinkStreamTableTrait.sql(FlinkStreamTableTrait.scala:98) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.cli.SqlClient$.handle(SqlClient.scala:30) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.core.scala.FlinkStreamTable$class.main(FlinkStreamTable.scala:53) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.cli.SqlClient$.main(SqlClient.scala:28) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.cli.SqlClient.main(SqlClient.scala) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist_2.12-1.13.2.jar:1.13.2]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.12-1.13.2.jar:1.13.2]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.12-1.13.2.jar:1.13.2]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:242) ~[flink-dist_2.12-1.13.2.jar:1.13.2]
	... 10 more
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_221]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_221]
	at com.streamxhub.streamx.flink.core.SqlError.<init>(SqlCommandParser.scala:377) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$.executeSql(FlinkSqlExecutor.scala:76) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.core.FlinkStreamTableTrait.sql(FlinkStreamTableTrait.scala:98) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.cli.SqlClient$.handle(SqlClient.scala:30) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.core.scala.FlinkStreamTable$class.main(FlinkStreamTable.scala:53) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.cli.SqlClient$.main(SqlClient.scala:28) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at com.streamxhub.streamx.flink.cli.SqlClient.main(SqlClient.scala) ~[streamx-flink-sqlclient-1.1.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist_2.12-1.13.2.jar:1.13.2]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.12-1.13.2.jar:1.13.2]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.12-1.13.2.jar:1.13.2]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:242) ~[flink-dist_2.12-1.13.2.jar:1.13.2]
	... 10 more
### Additional context
Add any other context about the problem here such as JVM track stack log.

### Requirement or improvement

- Please describe about your requirements or improvement suggestions.
希望能支持scala2.12版本

**Comment by Chen-bj** [comment]
Hello, Excuse me?
So far, on the dev branch, does it support flink scala 2.12？

After using the dev branch to build, I found an exception when launching the application: lanuch application failed, can no find streamx flex SqlClient jar in / opt / software / streamx console-service-1.2.3/client
