### ISSUE TITLE
[Bug] streamx-console v1.1.1 部署启动不成功

### ISSUE THREAD

**Issue by glacierck** [streamxhub/streamx#318]
*请在提交你的 issue 前，请回答以下问题，这有助于社区快速定位问题，谢谢！ 🙏*

### Environment Description（运行环境描述）
* **StreamX Version**: v1.1.1
* **JVM version** (`java -version`):v1.8
* **OS version** (`uname -a` if on a Unix-like system): centos7

### Bug Description（Bug 描述）
我在本地机器(mac,java15)进行的编译，对编译压缩包解压后发到测试集群机器，执行start.sh. 脚本无异常。但检查logs时发现以下异常，且页面无法访问1000服务。检查数据已经有部分初始化信息（不知道全不全），如下：

### How to Reproduce（如何重现这个 Bug） 
重现 Bug 现场的步骤，见描述。

### Additional context（额外的上下文信息）
2021-09-26 17:04:26 | INFO  | main | com.baomidou.dynamic.datasource.DynamicRoutingDataSource | [StreamX] closing dynamicDatasource  ing....
2021-09-26 17:04:26 | INFO  | main | com.zaxxer.hikari.HikariDataSource | [StreamX] primary - Shutdown initiated...
2021-09-26 17:04:26 | INFO  | main | com.zaxxer.hikari.HikariDataSource | [StreamX] primary - Shutdown completed.
2021-09-26 17:04:26 | INFO  | main | org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener | [StreamX] 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-09-26 17:04:26 | ERROR | main | org.springframework.boot.SpringApplication | [StreamX] Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'envInitializer': Unsatisfied dependency expressed through field 'settingService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Validate failed: Detected failed migration to version 1.1.2 (upgrade db)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1420)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at com.streamxhub.streamx.console.StreamXConsole.main(StreamXConsole.java:66)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Validate failed: Detected failed migration to version 1.1.2 (upgrade db)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:311)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
        ... 18 common frames omitted
Caused by: org.flywaydb.core.api.FlywayException: Validate failed: Detected failed migration to version 1.1.2 (upgrade db)
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:1482)
        at org.flywaydb.core.Flyway.access$100(Flyway.java:85)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1364)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
        ... 30 common frames omitted

### Requirement or improvement（诉求 & 改进建议）
- 我还没开始研究代码，不知道是我编译和部署环境是否存在差异导致的问题，还是说代码的问题。

**Comment by Al-assad** [comment]
@glacierck 这是一个错误的 flyway 更新文件，原本应该归属在 k8s-feature 开发分支中，由于疏忽出现在了 main 里，我们会在 1.2.0 里删除这个错误的文件。
