### ISSUE TITLE
[Bug] 项目初始化数据库异常

### ISSUE THREAD

**Issue by glacierck** [streamxhub/streamx#319]
*请在提交你的 issue 前，请回答以下问题，这有助于社区快速定位问题，谢谢！ 🙏*

### Environment Description（运行环境描述）
* **StreamX Version**: v1.1.1
* **JVM version** (`java -version`):1.8
* **OS version** (`uname -a` if on a Unix-like system):centos7

### Bug Description（Bug 描述）
项目第一期部署启动，第一份异常报告提示： ERROR o.f.core.internal.command.DbMigrate - [StreamX] Migration of schema `streamx` to version 1.1.2 - upgrade db failed! Please restore backups and roll back database and code!

### How to Reproduce（如何重现这个 Bug） 
见说明

### Additional context（额外的上下文信息）
K_IMAGE` varchar(255) NULL AFTER `K8S_NAMESPACE`' at line 4
Location   : db/migration/V1_1_2__upgrade_db.sql (/root/streamx-console-service-1.1.1/file:/root/streamx-console-service-1.1.1/lib/streamx-console-service-1.1.1.jar!/db/migration/V1_1_2__upgrade_db.sql)
Line       : 7
Statement  : ALTER TABLE `streamx`.`t_flink_app`
    ADD COLUMN `CLUSTER_ID` varchar(255) NULL AFTER `JOB_ID`,
    ADD COLUMN `K8S_NAMESPACE` varchar(255) NULL AFTER `CLUSTER_ID`
    ADD COLUMN `FLINK_IMAGE` varchar(255) NULL AFTER `K8S_NAMESPACE`

        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370)
        at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54)
        at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:284)
        at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:281)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
        at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:164)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:161)
        at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
        at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:147)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:155)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:161)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:139)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1395)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
        ... 30 common frames omitted
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: 
Migration V1_1_2__upgrade_db.sql failed
---------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ADD COLUMN `FLINK_IMAGE` varchar(255) NULL AFTER `K8S_NAMESPACE`' at line 4
Location   : db/migration/V1_1_2__upgrade_db.sql (/root/streamx-console-service-1.1.1/file:/root/streamx-console-service-1.1.1/lib/streamx-console-service-1.1.1.jar!/db/migration/V1_1_2__upgrade_db.sql)
Line       : 7
Statement  : ALTER TABLE `streamx`.`t_flink_app`
    ADD COLUMN `CLUSTER_ID` varchar(255) NULL AFTER `JOB_ID`,
    ADD COLUMN `K8S_NAMESPACE` varchar(255) NULL AFTER `CLUSTER_ID`
    ADD COLUMN `FLINK_IMAGE` varchar(255) NULL AFTER `K8S_NAMESPACE`

        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:253)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:202)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:125)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:77)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:367)
        ... 50 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ADD COLUMN `FLINK_IMAGE` varchar(255) NULL AFTER `K8S_NAMESPACE`' at line 4
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:235)
        at org.flywaydb.core.internal.sqlscript.StandardSqlStatement.execute(StandardSqlStatement.java:42)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:189)
        ... 53 common frames omitted

### Requirement or improvement（诉求 & 改进建议）
- 启动失败

**Comment by glacierck** [comment]
![image](https://user-images.githubusercontent.com/21599896/134802708-57a096aa-d175-4cd3-9308-b8e530cc64d1.png)
初步检查貌似是这里出问题了。/streamx/streamx-console/streamx-console-service/src/main/resources/db/migration/V1_1_2__upgrade_db.sql 这个迁移语法貌似有问题，第九行少了个逗号。

**Comment by wolfboys** [comment]
非常感谢你的报告,我们期望更多的开发者加入到建设中,你可以提交个pr,修复该问题
